quotes = [

# Struggle
{"text":"生存还是毁灭，这是一个值得思考的问题。","author":"莎士比亚","source":"哈姆雷特","year":1600,"type":"struggle","weight":0.8},
{"text":"唯一严肃的哲学问题是自杀。","author":"加缪","source":"西西弗神话","year":1942,"type":"struggle","weight":1.0},
{"text":"我与世界格格不入。","author":"卡夫卡","source":"日记","year":1910,"type":"struggle","weight":1.0},
{"text":"人类全部的困境在于不能安静地独处。","author":"帕斯卡","source":"思想录","year":1670,"type":"struggle","weight":1.1},
{"text":"我不属于任何地方。","author":"卡夫卡","source":"札记","year":1920,"type":"struggle","weight":1.1},
{"text":"世界让我厌倦。","author":"卡夫卡","source":"日记","year":1913,"type":"struggle","weight":1.0},
{"text":"一切都令人疲惫。","author":"卡夫卡","source":"日记","year":1914,"type":"struggle","weight":1.0},
{"text":"我无法理解这个世界。","author":"陀思妥耶夫斯基","source":"笔记","year":1864,"type":"struggle","weight":1.1},
{"text":"人是一个谜。","author":"陀思妥耶夫斯基","source":"作家日记","year":1873,"type":"struggle","weight":1.1},
{"text":"如果上帝不存在，一切皆被允许。","author":"陀思妥耶夫斯基","source":"卡拉马佐夫兄弟","year":1880,"type":"struggle","weight":1.2},
{"text":"我不能再忍受存在本身。","author":"萨特","source":"恶心","year":1938,"type":"struggle","weight":1.2},
{"text":"存在令人作呕。","author":"萨特","source":"恶心","year":1938,"type":"struggle","weight":1.2},
{"text":"我不知道自己是谁。","author":"卡夫卡","source":"札记","year":1922,"type":"struggle","weight":1.1},
{"text":"生活像一场漫长的失败。","author":"卡夫卡","source":"日记","year":1915,"type":"struggle","weight":1.1},
{"text":"人被抛入这个世界。","author":"海德格尔","source":"存在与时间","year":1927,"type":"struggle","weight":1.0},
{"text":"我感到自己被世界拒绝。","author":"卡夫卡","source":"书信","year":1917,"type":"struggle","weight":1.0},
{"text":"一切都没有答案。","author":"加缪","source":"随笔","year":1942,"type":"struggle","weight":1.1},
{"text":"荒诞是人与世界之间的对抗。","author":"加缪","source":"西西弗神话","year":1942,"type":"struggle","weight":1.2},
{"text":"我既不属于这里，也不属于那里。","author":"卡夫卡","source":"札记","year":1921,"type":"struggle","weight":1.1},
{"text":"我无法成为别人，也无法成为自己。","author":"卡夫卡","source":"札记","year":1920,"type":"struggle","weight":1.2},

# Acceptance
{"text":"世上只有一种英雄主义，就是认清生活的真相之后依然热爱生活。","author":"罗曼·罗兰","source":"约翰·克利斯朵夫","year":1915,"type":"acceptance","weight":1.5},
{"text":"必须想象西西弗是幸福的。","author":"加缪","source":"西西弗神话","year":1942,"type":"acceptance","weight":1.4},
{"text":"人不是为失败而生的。","author":"海明威","source":"老人与海","year":1952,"type":"acceptance","weight":1.3},
{"text":"在隆冬，我终于知道我身上有一个不可战胜的夏天。","author":"加缪","source":"随笔","year":1954,"type":"acceptance","weight":1.3},
{"text":"生活必须继续。","author":"卡夫卡","source":"札记","year":1920,"type":"acceptance","weight":1.3},
{"text":"即使如此，人仍然要活下去。","author":"加缪","source":"随笔","year":1942,"type":"acceptance","weight":1.3},
{"text":"重要的不是治愈，而是带着病痛活下去。","author":"加缪","source":"随笔","year":1942,"type":"acceptance","weight":1.4},
{"text":"我接受这个世界的不完美。","author":"托尔斯泰","source":"书信","year":1880,"type":"acceptance","weight":1.2},
{"text":"幸福在于忍耐。","author":"托尔斯泰","source":"札记","year":1875,"type":"acceptance","weight":1.2},
{"text":"活着本身就是一种胜利。","author":"海明威","source":"书信","year":1950,"type":"acceptance","weight":1.3},
{"text":"一切终将过去。","author":"托尔斯泰","source":"日记","year":1878,"type":"acceptance","weight":1.2},
{"text":"生活不会更容易，你只是变得更强。","author":"尼采","source":"札记","year":1885,"type":"acceptance","weight":1.3},
{"text":"你必须学会忍受生活。","author":"陀思妥耶夫斯基","source":"书信","year":1876,"type":"acceptance","weight":1.2},
{"text":"承受本身就是意义。","author":"加缪","source":"随笔","year":1942,"type":"acceptance","weight":1.4},
{"text":"继续走下去，是唯一的选择。","author":"卡夫卡","source":"札记","year":1921,"type":"acceptance","weight":1.3},

# Rebellion
{"text":"凡不能杀死我的，终将使我更强大。","author":"尼采","source":"偶像的黄昏","year":1888,"type":"rebellion","weight":1.4},
{"text":"当你凝视深渊时，深渊也在凝视你。","author":"尼采","source":"善恶的彼岸","year":1886,"type":"rebellion","weight":1.2},
{"text":"上帝死了。","author":"尼采","source":"快乐的科学","year":1882,"type":"rebellion","weight":1.1},
{"text":"宁在地狱为王，不在天堂为臣。","author":"弥尔顿","source":"失乐园","year":1667,"type":"rebellion","weight":1.3},
{"text":"我要成为我自己。","author":"尼采","source":"查拉图斯特拉如是说","year":1883,"type":"rebellion","weight":1.3},
{"text":"成为你自己。","author":"尼采","source":"札记","year":1884,"type":"rebellion","weight":1.3},
{"text":"我选择反抗。","author":"加缪","source":"反抗者","year":1951,"type":"rebellion","weight":1.3},
{"text":"自由是自己赋予自己的。","author":"萨特","source":"存在主义是一种人道主义","year":1946,"type":"rebellion","weight":1.2},
{"text":"我拒绝顺从。","author":"加缪","source":"随笔","year":1942,"type":"rebellion","weight":1.2},
{"text":"人必须创造自己的意义。","author":"萨特","source":"存在与虚无","year":1943,"type":"rebellion","weight":1.3},

# Statement
{"text":"我思故我在。","author":"笛卡尔","source":"第一哲学沉思集","year":1641,"type":"statement","weight":1.1},
{"text":"人只不过是一根芦苇，但他是一根会思想的芦苇。","author":"帕斯卡","source":"思想录","year":1670,"type":"statement","weight":1.1},
{"text":"他人即地狱。","author":"萨特","source":"禁闭","year":1944,"type":"statement","weight":1.2},
{"text":"语言是存在的家。","author":"海德格尔","source":"人文主义书信","year":1947,"type":"statement","weight":1.1},
{"text":"人是社会关系的总和。","author":"马克思","source":"德意志意识形态","year":1845,"type":"statement","weight":1.1},
{"text":"没有人是一座孤岛。","author":"约翰·多恩","source":"沉思录","year":1624,"type":"statement","weight":1.2},
{"text":"凡不可说的，必须保持沉默。","author":"维特根斯坦","source":"逻辑哲学论","year":1921,"type":"statement","weight":1.1},
{"text":"世界是一个舞台。","author":"莎士比亚","source":"皆大欢喜","year":1599,"type":"statement","weight":1.0},
{"text":"知识就是力量。","author":"培根","source":"随笔","year":1597,"type":"statement","weight":1.0},
{"text":"幸福的家庭都是相似的，不幸的家庭各有各的不幸。","author":"托尔斯泰","source":"安娜·卡列尼娜","year":1877,"type":"statement","weight":1.2}

]
